version: '3.8'

services:
  app:
    image: node:18  # Use appropriate Node.js version
    container_name: my-node-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"  # Change port if needed
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm install && npm start"
    restart: unless-stopped
    depends_on:
      - mongo  # Remove this if not using MongoDB

  mongo:
    image: mongo:6
    container_name: my-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password  # Change this!

volumes:
  mongo_data:
