version: '3'
services:
  app:
    container_name: my-node-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Avoid overwriting node_modules
    restart: unless-stopped
